/***************************************************************************
 * The contents of this file were generated with Amplify Studio.           *
 * Please refrain from making any modifications to this file.              *
 * Any changes to this file will be overwritten when running amplify pull. *
 **************************************************************************/

/* eslint-disable */
import * as React from "react";
import { getOverrideProps } from "./utils";
import { Icon, Image, Text, View } from "@aws-amplify/ui-react";
export default function Leadership(props) {
  const { overrides, ...rest } = props;
  return (
    <View
      width="1280px"
      height="832px"
      display="block"
      gap="unset"
      alignItems="unset"
      justifyContent="unset"
      overflow="hidden"
      position="relative"
      padding="0px 0px 0px 0px"
      backgroundColor="rgba(255,255,255,1)"
      {...getOverrideProps(overrides, "Leadership")}
      {...rest}
    >
      <Image
        width="1280px"
        height="860px"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="-14px"
        left="0px"
        padding="0px 0px 0px 0px"
        objectFit="cover"
        {...getOverrideProps(overrides, "image 7")}
      ></Image>
      <Text
        fontFamily="Irish Grover"
        fontSize="100px"
        fontWeight="400"
        color="rgba(161,128,233,1)"
        lineHeight="120.8984375px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="695px"
        height="120px"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="56px"
        left="409px"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="leadership"
        {...getOverrideProps(overrides, "leadership")}
      ></Text>
      <Icon
        width="1050px"
        height="530px"
        viewBox={{ minX: 0, minY: 0, width: 1050, height: 530 }}
        paths={[
          {
            d: "M0 20C0 8.95429 8.95431 0 20 0L1030 0C1041.05 0 1050 8.95431 1050 20L1050 510C1050 521.046 1041.05 530 1030 530L20 530C8.9543 530 0 521.046 0 510L0 20Z",
            fill: "rgba(10,0,51,1)",
            fillRule: "nonzero",
          },
        ]}
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="210px"
        left="129px"
        {...getOverrideProps(overrides, "Rectangle 5")}
      ></Icon>
      <View
        padding="0px 0px 0px 0px"
        width="450px"
        height="48px"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="249px"
        left="165px"
        {...getOverrideProps(overrides, "Group 15704")}
      >
        <View
          width="450px"
          height="48px"
          display="block"
          gap="unset"
          alignItems="unset"
          justifyContent="unset"
          position="absolute"
          top="0px"
          left="0px"
          border="4px SOLID rgba(58,0,137,1)"
          boxShadow="0px 4px 10px rgba(0.6313725709915161, 0.501960813999176, 0.9137254953384399, 1)"
          borderRadius="10px"
          padding="0px 0px 0px 0px"
          backgroundColor="rgba(32,16,99,1)"
          {...getOverrideProps(overrides, "Rectangle 133848620")}
        ></View>
        <Text
          fontFamily="Irish Grover"
          fontSize="30px"
          fontWeight="400"
          color="rgba(255,255,255,1)"
          lineHeight="36.26953125px"
          textAlign="left"
          display="block"
          direction="column"
          justifyContent="unset"
          width="unset"
          height="unset"
          gap="unset"
          alignItems="unset"
          position="absolute"
          top="2px"
          left="22px"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="user101"
          {...getOverrideProps(overrides, "user1013848632")}
        ></Text>
        <Text
          fontFamily="Irish Grover"
          fontSize="30px"
          fontWeight="400"
          color="rgba(255,255,255,1)"
          lineHeight="36.26953125px"
          textAlign="left"
          display="block"
          direction="column"
          justifyContent="unset"
          width="unset"
          height="unset"
          gap="unset"
          alignItems="unset"
          position="absolute"
          top="2px"
          left="374px"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="700"
          {...getOverrideProps(overrides, "7003848634")}
        ></Text>
      </View>
      <View
        padding="0px 0px 0px 0px"
        width="450px"
        height="48px"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="332px"
        left="165px"
        {...getOverrideProps(overrides, "Group 15705")}
      >
        <View
          width="450px"
          height="48px"
          display="block"
          gap="unset"
          alignItems="unset"
          justifyContent="unset"
          position="absolute"
          top="0px"
          left="0px"
          border="4px SOLID rgba(58,0,137,1)"
          boxShadow="0px 4px 10px rgba(0.6313725709915161, 0.501960813999176, 0.9137254953384399, 1)"
          borderRadius="10px"
          padding="0px 0px 0px 0px"
          backgroundColor="rgba(32,16,99,1)"
          {...getOverrideProps(overrides, "Rectangle 133849144")}
        ></View>
        <Text
          fontFamily="Irish Grover"
          fontSize="30px"
          fontWeight="400"
          color="rgba(255,255,255,1)"
          lineHeight="36.26953125px"
          textAlign="left"
          display="block"
          direction="column"
          justifyContent="unset"
          width="unset"
          height="unset"
          gap="unset"
          alignItems="unset"
          position="absolute"
          top="2px"
          left="22px"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="user101"
          {...getOverrideProps(overrides, "user1013849145")}
        ></Text>
        <Text
          fontFamily="Irish Grover"
          fontSize="30px"
          fontWeight="400"
          color="rgba(255,255,255,1)"
          lineHeight="36.26953125px"
          textAlign="left"
          display="block"
          direction="column"
          justifyContent="unset"
          width="unset"
          height="unset"
          gap="unset"
          alignItems="unset"
          position="absolute"
          top="2px"
          left="374px"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="700"
          {...getOverrideProps(overrides, "7003849146")}
        ></Text>
      </View>
      <View
        padding="0px 0px 0px 0px"
        width="450px"
        height="48px"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="415px"
        left="165px"
        {...getOverrideProps(overrides, "Group 15706")}
      >
        <View
          width="450px"
          height="48px"
          display="block"
          gap="unset"
          alignItems="unset"
          justifyContent="unset"
          position="absolute"
          top="0px"
          left="0px"
          border="4px SOLID rgba(58,0,137,1)"
          boxShadow="0px 4px 10px rgba(0.6313725709915161, 0.501960813999176, 0.9137254953384399, 1)"
          borderRadius="10px"
          padding="0px 0px 0px 0px"
          backgroundColor="rgba(32,16,99,1)"
          {...getOverrideProps(overrides, "Rectangle 133849149")}
        ></View>
        <Text
          fontFamily="Irish Grover"
          fontSize="30px"
          fontWeight="400"
          color="rgba(255,255,255,1)"
          lineHeight="36.26953125px"
          textAlign="left"
          display="block"
          direction="column"
          justifyContent="unset"
          width="unset"
          height="unset"
          gap="unset"
          alignItems="unset"
          position="absolute"
          top="2px"
          left="22px"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="user101"
          {...getOverrideProps(overrides, "user1013849150")}
        ></Text>
        <Text
          fontFamily="Irish Grover"
          fontSize="30px"
          fontWeight="400"
          color="rgba(255,255,255,1)"
          lineHeight="36.26953125px"
          textAlign="left"
          display="block"
          direction="column"
          justifyContent="unset"
          width="unset"
          height="unset"
          gap="unset"
          alignItems="unset"
          position="absolute"
          top="2px"
          left="374px"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="700"
          {...getOverrideProps(overrides, "7003849151")}
        ></Text>
      </View>
      <View
        padding="0px 0px 0px 0px"
        width="450px"
        height="48px"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="498px"
        left="165px"
        {...getOverrideProps(overrides, "Group 15707")}
      >
        <View
          width="450px"
          height="48px"
          display="block"
          gap="unset"
          alignItems="unset"
          justifyContent="unset"
          position="absolute"
          top="0px"
          left="0px"
          border="4px SOLID rgba(58,0,137,1)"
          boxShadow="0px 4px 10px rgba(0.6313725709915161, 0.501960813999176, 0.9137254953384399, 1)"
          borderRadius="10px"
          padding="0px 0px 0px 0px"
          backgroundColor="rgba(32,16,99,1)"
          {...getOverrideProps(overrides, "Rectangle 133849154")}
        ></View>
        <Text
          fontFamily="Irish Grover"
          fontSize="30px"
          fontWeight="400"
          color="rgba(255,255,255,1)"
          lineHeight="36.26953125px"
          textAlign="left"
          display="block"
          direction="column"
          justifyContent="unset"
          width="unset"
          height="unset"
          gap="unset"
          alignItems="unset"
          position="absolute"
          top="2px"
          left="22px"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="user101"
          {...getOverrideProps(overrides, "user1013849155")}
        ></Text>
        <Text
          fontFamily="Irish Grover"
          fontSize="30px"
          fontWeight="400"
          color="rgba(255,255,255,1)"
          lineHeight="36.26953125px"
          textAlign="left"
          display="block"
          direction="column"
          justifyContent="unset"
          width="unset"
          height="unset"
          gap="unset"
          alignItems="unset"
          position="absolute"
          top="2px"
          left="374px"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="700"
          {...getOverrideProps(overrides, "7003849156")}
        ></Text>
      </View>
      <View
        padding="0px 0px 0px 0px"
        width="450px"
        height="48px"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="581px"
        left="165px"
        {...getOverrideProps(overrides, "Group 15708")}
      >
        <View
          width="450px"
          height="48px"
          display="block"
          gap="unset"
          alignItems="unset"
          justifyContent="unset"
          position="absolute"
          top="0px"
          left="0px"
          border="4px SOLID rgba(58,0,137,1)"
          boxShadow="0px 4px 10px rgba(0.6313725709915161, 0.501960813999176, 0.9137254953384399, 1)"
          borderRadius="10px"
          padding="0px 0px 0px 0px"
          backgroundColor="rgba(32,16,99,1)"
          {...getOverrideProps(overrides, "Rectangle 133849159")}
        ></View>
        <Text
          fontFamily="Irish Grover"
          fontSize="30px"
          fontWeight="400"
          color="rgba(255,255,255,1)"
          lineHeight="36.26953125px"
          textAlign="left"
          display="block"
          direction="column"
          justifyContent="unset"
          width="unset"
          height="unset"
          gap="unset"
          alignItems="unset"
          position="absolute"
          top="2px"
          left="22px"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="user101"
          {...getOverrideProps(overrides, "user1013849160")}
        ></Text>
        <Text
          fontFamily="Irish Grover"
          fontSize="30px"
          fontWeight="400"
          color="rgba(255,255,255,1)"
          lineHeight="36.26953125px"
          textAlign="left"
          display="block"
          direction="column"
          justifyContent="unset"
          width="unset"
          height="unset"
          gap="unset"
          alignItems="unset"
          position="absolute"
          top="2px"
          left="374px"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="700"
          {...getOverrideProps(overrides, "7003849161")}
        ></Text>
      </View>
      <View
        padding="0px 0px 0px 0px"
        width="450px"
        height="48px"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="664px"
        left="160px"
        {...getOverrideProps(overrides, "Group 15709")}
      >
        <View
          width="450px"
          height="48px"
          display="block"
          gap="unset"
          alignItems="unset"
          justifyContent="unset"
          position="absolute"
          top="0px"
          left="0px"
          border="4px SOLID rgba(58,0,137,1)"
          boxShadow="0px 4px 10px rgba(0.6313725709915161, 0.501960813999176, 0.9137254953384399, 1)"
          borderRadius="10px"
          padding="0px 0px 0px 0px"
          backgroundColor="rgba(32,16,99,1)"
          {...getOverrideProps(overrides, "Rectangle 133849164")}
        ></View>
        <Text
          fontFamily="Irish Grover"
          fontSize="30px"
          fontWeight="400"
          color="rgba(255,255,255,1)"
          lineHeight="36.26953125px"
          textAlign="left"
          display="block"
          direction="column"
          justifyContent="unset"
          width="unset"
          height="unset"
          gap="unset"
          alignItems="unset"
          position="absolute"
          top="2px"
          left="22px"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="user101"
          {...getOverrideProps(overrides, "user1013849165")}
        ></Text>
        <Text
          fontFamily="Irish Grover"
          fontSize="30px"
          fontWeight="400"
          color="rgba(255,255,255,1)"
          lineHeight="36.26953125px"
          textAlign="left"
          display="block"
          direction="column"
          justifyContent="unset"
          width="unset"
          height="unset"
          gap="unset"
          alignItems="unset"
          position="absolute"
          top="2px"
          left="374px"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="700"
          {...getOverrideProps(overrides, "7003849166")}
        ></Text>
      </View>
      <View
        padding="0px 0px 0px 0px"
        width="450px"
        height="48px"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="249px"
        left="686px"
        {...getOverrideProps(overrides, "Group 15710")}
      >
        <View
          width="450px"
          height="48px"
          display="block"
          gap="unset"
          alignItems="unset"
          justifyContent="unset"
          position="absolute"
          top="0px"
          left="0px"
          border="4px SOLID rgba(58,0,137,1)"
          boxShadow="0px 4px 10px rgba(0.6313725709915161, 0.501960813999176, 0.9137254953384399, 1)"
          borderRadius="10px"
          padding="0px 0px 0px 0px"
          backgroundColor="rgba(32,16,99,1)"
          {...getOverrideProps(overrides, "Rectangle 133849169")}
        ></View>
        <Text
          fontFamily="Irish Grover"
          fontSize="30px"
          fontWeight="400"
          color="rgba(255,255,255,1)"
          lineHeight="36.26953125px"
          textAlign="left"
          display="block"
          direction="column"
          justifyContent="unset"
          width="unset"
          height="unset"
          gap="unset"
          alignItems="unset"
          position="absolute"
          top="2px"
          left="22px"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="user101"
          {...getOverrideProps(overrides, "user1013849170")}
        ></Text>
        <Text
          fontFamily="Irish Grover"
          fontSize="30px"
          fontWeight="400"
          color="rgba(255,255,255,1)"
          lineHeight="36.26953125px"
          textAlign="left"
          display="block"
          direction="column"
          justifyContent="unset"
          width="unset"
          height="unset"
          gap="unset"
          alignItems="unset"
          position="absolute"
          top="2px"
          left="374px"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="700"
          {...getOverrideProps(overrides, "7003849171")}
        ></Text>
      </View>
      <View
        padding="0px 0px 0px 0px"
        width="450px"
        height="48px"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="332px"
        left="686px"
        {...getOverrideProps(overrides, "Group 15711")}
      >
        <View
          width="450px"
          height="48px"
          display="block"
          gap="unset"
          alignItems="unset"
          justifyContent="unset"
          position="absolute"
          top="0px"
          left="0px"
          border="4px SOLID rgba(58,0,137,1)"
          boxShadow="0px 4px 10px rgba(0.6313725709915161, 0.501960813999176, 0.9137254953384399, 1)"
          borderRadius="10px"
          padding="0px 0px 0px 0px"
          backgroundColor="rgba(32,16,99,1)"
          {...getOverrideProps(overrides, "Rectangle 133849173")}
        ></View>
        <Text
          fontFamily="Irish Grover"
          fontSize="30px"
          fontWeight="400"
          color="rgba(255,255,255,1)"
          lineHeight="36.26953125px"
          textAlign="left"
          display="block"
          direction="column"
          justifyContent="unset"
          width="unset"
          height="unset"
          gap="unset"
          alignItems="unset"
          position="absolute"
          top="2px"
          left="22px"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="user101"
          {...getOverrideProps(overrides, "user1013849174")}
        ></Text>
        <Text
          fontFamily="Irish Grover"
          fontSize="30px"
          fontWeight="400"
          color="rgba(255,255,255,1)"
          lineHeight="36.26953125px"
          textAlign="left"
          display="block"
          direction="column"
          justifyContent="unset"
          width="unset"
          height="unset"
          gap="unset"
          alignItems="unset"
          position="absolute"
          top="2px"
          left="374px"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="700"
          {...getOverrideProps(overrides, "7003849175")}
        ></Text>
      </View>
      <View
        padding="0px 0px 0px 0px"
        width="450px"
        height="48px"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="415px"
        left="686px"
        {...getOverrideProps(overrides, "Group 15712")}
      >
        <View
          width="450px"
          height="48px"
          display="block"
          gap="unset"
          alignItems="unset"
          justifyContent="unset"
          position="absolute"
          top="0px"
          left="0px"
          border="4px SOLID rgba(58,0,137,1)"
          boxShadow="0px 4px 10px rgba(0.6313725709915161, 0.501960813999176, 0.9137254953384399, 1)"
          borderRadius="10px"
          padding="0px 0px 0px 0px"
          backgroundColor="rgba(32,16,99,1)"
          {...getOverrideProps(overrides, "Rectangle 133849177")}
        ></View>
        <Text
          fontFamily="Irish Grover"
          fontSize="30px"
          fontWeight="400"
          color="rgba(255,255,255,1)"
          lineHeight="36.26953125px"
          textAlign="left"
          display="block"
          direction="column"
          justifyContent="unset"
          width="unset"
          height="unset"
          gap="unset"
          alignItems="unset"
          position="absolute"
          top="2px"
          left="22px"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="user101"
          {...getOverrideProps(overrides, "user1013849178")}
        ></Text>
        <Text
          fontFamily="Irish Grover"
          fontSize="30px"
          fontWeight="400"
          color="rgba(255,255,255,1)"
          lineHeight="36.26953125px"
          textAlign="left"
          display="block"
          direction="column"
          justifyContent="unset"
          width="unset"
          height="unset"
          gap="unset"
          alignItems="unset"
          position="absolute"
          top="2px"
          left="374px"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="700"
          {...getOverrideProps(overrides, "7003849179")}
        ></Text>
      </View>
      <View
        padding="0px 0px 0px 0px"
        width="450px"
        height="48px"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="498px"
        left="686px"
        {...getOverrideProps(overrides, "Group 15713")}
      >
        <View
          width="450px"
          height="48px"
          display="block"
          gap="unset"
          alignItems="unset"
          justifyContent="unset"
          position="absolute"
          top="0px"
          left="0px"
          border="4px SOLID rgba(58,0,137,1)"
          boxShadow="0px 4px 10px rgba(0.6313725709915161, 0.501960813999176, 0.9137254953384399, 1)"
          borderRadius="10px"
          padding="0px 0px 0px 0px"
          backgroundColor="rgba(32,16,99,1)"
          {...getOverrideProps(overrides, "Rectangle 133849181")}
        ></View>
        <Text
          fontFamily="Irish Grover"
          fontSize="30px"
          fontWeight="400"
          color="rgba(255,255,255,1)"
          lineHeight="36.26953125px"
          textAlign="left"
          display="block"
          direction="column"
          justifyContent="unset"
          width="unset"
          height="unset"
          gap="unset"
          alignItems="unset"
          position="absolute"
          top="2px"
          left="22px"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="user101"
          {...getOverrideProps(overrides, "user1013849182")}
        ></Text>
        <Text
          fontFamily="Irish Grover"
          fontSize="30px"
          fontWeight="400"
          color="rgba(255,255,255,1)"
          lineHeight="36.26953125px"
          textAlign="left"
          display="block"
          direction="column"
          justifyContent="unset"
          width="unset"
          height="unset"
          gap="unset"
          alignItems="unset"
          position="absolute"
          top="2px"
          left="374px"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="700"
          {...getOverrideProps(overrides, "7003849183")}
        ></Text>
      </View>
      <View
        padding="0px 0px 0px 0px"
        width="450px"
        height="48px"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="581px"
        left="686px"
        {...getOverrideProps(overrides, "Group 15714")}
      >
        <View
          width="450px"
          height="48px"
          display="block"
          gap="unset"
          alignItems="unset"
          justifyContent="unset"
          position="absolute"
          top="0px"
          left="0px"
          border="4px SOLID rgba(58,0,137,1)"
          boxShadow="0px 4px 10px rgba(0.6313725709915161, 0.501960813999176, 0.9137254953384399, 1)"
          borderRadius="10px"
          padding="0px 0px 0px 0px"
          backgroundColor="rgba(32,16,99,1)"
          {...getOverrideProps(overrides, "Rectangle 133849185")}
        ></View>
        <Text
          fontFamily="Irish Grover"
          fontSize="30px"
          fontWeight="400"
          color="rgba(255,255,255,1)"
          lineHeight="36.26953125px"
          textAlign="left"
          display="block"
          direction="column"
          justifyContent="unset"
          width="unset"
          height="unset"
          gap="unset"
          alignItems="unset"
          position="absolute"
          top="2px"
          left="22px"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="user101"
          {...getOverrideProps(overrides, "user1013849186")}
        ></Text>
        <Text
          fontFamily="Irish Grover"
          fontSize="30px"
          fontWeight="400"
          color="rgba(255,255,255,1)"
          lineHeight="36.26953125px"
          textAlign="left"
          display="block"
          direction="column"
          justifyContent="unset"
          width="unset"
          height="unset"
          gap="unset"
          alignItems="unset"
          position="absolute"
          top="2px"
          left="374px"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="700"
          {...getOverrideProps(overrides, "7003849187")}
        ></Text>
      </View>
      <View
        padding="0px 0px 0px 0px"
        width="450px"
        height="48px"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="664px"
        left="681px"
        {...getOverrideProps(overrides, "Group 15715")}
      >
        <View
          width="450px"
          height="48px"
          display="block"
          gap="unset"
          alignItems="unset"
          justifyContent="unset"
          position="absolute"
          top="0px"
          left="0px"
          border="4px SOLID rgba(58,0,137,1)"
          boxShadow="0px 4px 10px rgba(0.6313725709915161, 0.501960813999176, 0.9137254953384399, 1)"
          borderRadius="10px"
          padding="0px 0px 0px 0px"
          backgroundColor="rgba(32,16,99,1)"
          {...getOverrideProps(overrides, "Rectangle 133849189")}
        ></View>
        <Text
          fontFamily="Irish Grover"
          fontSize="30px"
          fontWeight="400"
          color="rgba(255,255,255,1)"
          lineHeight="36.26953125px"
          textAlign="left"
          display="block"
          direction="column"
          justifyContent="unset"
          width="unset"
          height="unset"
          gap="unset"
          alignItems="unset"
          position="absolute"
          top="2px"
          left="22px"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="user101"
          {...getOverrideProps(overrides, "user1013849190")}
        ></Text>
        <Text
          fontFamily="Irish Grover"
          fontSize="30px"
          fontWeight="400"
          color="rgba(255,255,255,1)"
          lineHeight="36.26953125px"
          textAlign="left"
          display="block"
          direction="column"
          justifyContent="unset"
          width="unset"
          height="unset"
          gap="unset"
          alignItems="unset"
          position="absolute"
          top="2px"
          left="374px"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="700"
          {...getOverrideProps(overrides, "7003849191")}
        ></Text>
      </View>
    </View>
  );
}
